### ISSUE TITLE
NameError: global name 'quit' is not defined

### ISSUE THREAD

**Issue by reinzor** [pozyxLabs/Pozyx-Python-library#39]
https://github.com/pozyxLabs/Pozyx-Python-library/blob/master/pypozyx/pozyx_serial.py#L183
```
NameError: global name 'quit' is not defined
```

**Comment by laurentva** [comment]
Hey Rein,

I solved this in the new release (see Rokus's update). Since you're probably the end user of Rokus's implementation (same company?) you'll likely have to change the SerialException in your catch to PozyxConnectionError (or PozyxException if you don't need it as finegrained).

I'll close this once I've released
